### ISSUE TITLE
no detected spatial_community, empty heatmap

### ISSUE THREAD

**Issue by Elena983** [BodenmillerGroup/IMCDataAnalysis#95] opened 2024-02-07 11:08 UTC
Hello, I can't generate the spatial community values for spatial analysis.
Could you please check my sce object
[spe.rds.zip](https://github.com/BodenmillerGroup/IMCDataAnalysis/files/14192793/spe.rds.zip)

and the 2nd one is about heamap

`celltype_mean <- aggregateAcrossCells(as(spe, "SingleCellExperiment"),
ids = spe$cluster_celltype,
statistics = "mean",
use.assay.type = "exprs",
subset.row = rownames(spe)[rowData(spe)$marker_class == "type"])

h_type <- Heatmap(t(assay(celltype_mean, "exprs")),
column_title = "type_markers",
col = col_exprs,
name= "mean exprs",
show_row_names = TRUE,
show_column_names = TRUE)

draw(h_type)`

and resulting in the empty heatmap
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/68946912/ffbfcedd-759f-40e2-8727-0a37a9819457)

**Comment by SchulzDan** [comment] 2024-02-08 10:23
Hi @Elena983

I cannot reproduce your error. I downloaded your spe object and ran the code you shared above with one change. I don't know what col_exprs is and I ran the code like this: 
`h_type <- Heatmap(t(assay(celltype_mean, "exprs")),
                  column_title = "type_markers",
                  #col = col_exprs,
                  name= "mean exprs",
                  show_row_names = TRUE,
                  show_column_names = TRUE)

draw(h_type)`

which resulted in this heatmap:
![heatmap](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/18529618/508f88bf-9f38-4017-bc6f-74f6c689066b)

from my heampa you can see that values range from 4 to 8. however in your heatmap you stop plotting at 4 which is why everything is yellow. adapt the color range in the your custom scale. you could simply use the viridis package and plot like this:

`h_type <- Heatmap(t(assay(celltype_mean, "exprs")),
                  column_title = "type_markers",
                  col =viridis(100),
                  name= "mean exprs",
                  show_row_names = TRUE,
                  show_column_names = TRUE)`

Best,
Daniel

**Comment by Elena983** [comment] 2024-02-08 12:31
Thank you,
it did work

could you see my spatial communities?
Cannot do the spatial analysis

**Comment by SchulzDan** [comment] 2024-02-08 14:01
Hi,

Could you please specify the problem? I cannot guess or try to reverse engineer with this information.

Best,
Daniel

**Comment by Elena983** [comment] 2024-02-09 15:41
Thank you, Daniel

I ran the spatial analysis, but in my spe object, there are only NAs in the spe$spatial_community column.

And I received 
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/68946912/f086b9ec-f97b-4ac8-ac98-b9e07953f803)

![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/68946912/62cd0341-b11a-4c08-bfe9-db163c34e4c4)

But I generated all documents: graphs from the Steinbock docker pipeline.

**Comment by SchulzDan** [comment] 2024-02-11 19:25
Hi @Elena983,

From this still limited information it seems that something went wrong with your neighborhood detection in steinbock. Or potentially the cells are on average further away from each other and with the standard parameters you do not capture many neighbors. If you simply plot your images with the edges using the plotSpatial functin you can see that you do not have many connected cells in your neighborhood graph. However, in the knn_interaction_graph all is fine since this is, if not specified distance independent. Please check your average distances between cells and adapt code accordingly.
Also, are these TMA samples? From the look of the round cell structures it seems like it. However, there are many cells surrounding your what looks like TMA punches which would not make sense. Maybe double check.

Best,
Daniel

**Comment by Elena983** [comment] 2024-02-13 10:40
I have a lot of cells, and probably because of that, I don't see any connections
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/68946912/e246e629-d70d-4040-9e5f-a0a4177867b1)
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/68946912/96b87264-9adf-4a9c-8e14-19590ff5e846)
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/68946912/1afa8147-0846-4d46-8cea-6ea20c114a64)
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/68946912/ed5467ee-a9d9-440c-b1e1-0223ab3a723d)

How to check the average distances and where to adapt the code?

Yes, there are the TMA cores
And I don't know why there are cells in the plot, as I cropped the round area only.

**Comment by SchulzDan** [comment] 2024-02-22 19:15
Hi @Elena983,

two suggestions before I will close the issue.
1) Please check your raw data images and masks. If you are working with TMAs there should be 0 cells outside the TMA core. If there are, then there is something funky going on with the segmentation and that does not seem like a good start. A place to start plotting markers and masks would be cytomapper.
2) steinbock default parameters for segmentation and neighborhood detection are optimized for IMC. Are you working with IMC here? If not, then simply you may have higher resolution and therefore the standard expansion in steinbock would no capture many neighbors per cell. that would explain why the graph is not really working. in that case you could re-run with a reasonable distance parameter.
Hope that helps.
Best,
Daniel

**Closed as completed by SchulzDan** 2024-02-22 19:15 UTC
